server:
  port: 8001

spring:
  application:
    name: app1
  datasource:
    url: jdbc:mysql://localhost:3306/app1?characterEncoding=utf8&useSSL=false
    username: root
    password: yunaxiaozhou1
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource

mybatis:
  type-aliases-package: com.allen.app1.domain
  type-handlers-package: com.allen.app1.typehandler
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 60

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

