spring:
  application:
    name: transaction-message-service-web

  aop:
    proxy-target-class: true
    auto: true
  thymeleaf:
    mode: HTML
    suffix: .html
    cache: false
server:
  port: 8008

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 30000
        loggerLevel: basic

ribbon:
  ReadTimeout: 30000
  SocketTimeout: 10000
  ConnectTimeout: 10000

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 100000
