server:
  port: 8002

spring:
  application:
    name: app2
  datasource:
    url: jdbc:mysql://localhost:3306/app2?characterEncoding=utf8&useSSL=false
    username: root
    password: yunaxiaozhou1
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
  rabbitmq:
    host: localhost
    port: 5672
    username: allen
    password: yunaxiaozhou1

mybatis:
  type-aliases-package: com.allen.app2.domain
  type-handlers-package: com.allen.app2.typehandler
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 60

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/